### ISSUE TITLE
throwOnError doesn't Katex exceptions

### ISSUE THREAD

**Issue by vhf** [Rokt33r/remark-math#10]
Here is what I ran into:

```js
   const processor = remark()
     .use(math)
     .use(remark2rehype)
     .use(rehypeKatex, {
       throwOnError: false
     })
     .use(stringify)
 
   const targetText = '$ê$'
 
   processor.processSync(targetText)
```

Here is a failing test case: https://github.com/vhf/remark-math/commit/03becb26113f235efc46119d2f183106ffd03f69

Pulling this commit and running tests crashes rehype-katex. Here is the branch: https://github.com/vhf/remark-math/tree/throw-on-error

**Comment by Rokt33r** [comment]
Thanks for reporting. I'll check it today evening! 😄

**Comment by Rokt33r** [comment]
Actually there is some fall back of KaTeX. But, it doesn't seem to be cover all of cases. Instead of show error, I think showing the original input with high-lightening would be easy to understand, for user, what they've done wrong.

<img width="494" alt="screen shot 2017-04-05 at 23 34 25" src="https://cloud.githubusercontent.com/assets/5865853/24710557/6ef99cae-1a58-11e7-8133-edce3a643119.png">

**Comment by Rokt33r** [comment]
@vhf Be aware.
I'm going to setting `inlineMathDouble` class of `remark-math` to be optional just like `rehype-katex doing`.
Although it is not harmful, many people would be confused because there are 2 classes.

**Comment by vhf** [comment]
@Rokt33r Sure, thanks for the heads up!

**Comment by Rokt33r** [comment]
@vhf I fixed. Also, I renamed options. You can check here.
https://github.com/Rokt33r/remark-math#usage
